server:
  port: 9999
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/meeting?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: root
    password: ssafy
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        default_batch_fetch_size: 1000 # 최적화 옵션
  sql:
    init:
      encoding: UTF-8

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: fbb08611d97dc25ae84406583996ba60
#            client-secret: 7OK7BXboZznRDYqhLfJG2tNzT5QLKiLS
            redirect-uri: http://localhost:9999/api/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            client-name: Kakao
            scope: profile_nickname, profile_image, account_email

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

logging:
  level:
    org.hibernate.SQL: debug

cloud:
  aws:
    s3:
      bucket: tag-u #tagyou
    stack.auto: false
    region.static: ap-northeast-2
    credentials:
      accessKey: AKIA4S2XBYFDNSFC7XBK
      secretKey: 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
